/****************************************************
 *
 * ****     ***     ****    *   *    *****    *****
 * *  *    *   *   *        ****     ***        *
 * *   *    ***     ****    *   *    *****      *
 *
 * student_server.h
 * 2024-07-24 02:16:14
 * Generated by rocket framework rocket_generator.py
 * Do not edit !!!
****************************************************/




#include <google/protobuf/service.h>
#include <memory>
#include <rocket/common/log.h>
#include <rocket/common/config.h>
#include <rocket/net/tcp/net_addr.h>
#include <rocket/net/tcp/tcp_server.h>
#include <rocket/net/rpc/rpc_dispatcher.h>
#include "service/student_server.h"

int main(int argc, char* argv[]) {

  if (argc != 2) {
    printf("Start student_server error, argc not 2 \n");
    printf("Start like this: \n");
    printf("./student_server 12345 \n");
    return 0;
  }

  rocket::Logger::InitGlobalLogger();

  rocket::RpcDispatcher::GetRpcDispatcher()->registerService(std::make_shared<student_server::StudentServiceImpl>());

  rocket::IPNetAddr::s_ptr addr = std::make_shared<rocket::IPNetAddr>("127.0.0.1", autoi(argv[1]));

  rocket::TcpServer tcp_server(addr);

  tcp_server.start();

  return 0;
}